apiVersion: batch/v1
kind: Job
metadata:
  name: __SERVICE_NAME__-dbmigration
  namespace: __TEAM_NAME__
spec:
  template:
    spec:
      containers:
      - name: __SERVICE_NAME__-dbmigration
        image: __MIGRATION_VERSION__
        env:
        - name: POSTGRES_HOST
          value: "${SHARED_POSTGRES_SERVER_01}.postgres.database.azure.com"
        - name: SCHEMA_NAME
          value: ${POSTGRES_SCHEMA_NAME}
        - name: POSTGRES_DB
          value: ${POSTGRES_DB}
        - name: POSTGRES_PORT
          value: "${POSTGRES_PORT}"
        - name: SCHEMA_USERNAME
          value: "AAG-Azure-ADP-__TEAM_NAME__-__ENVIRONMENT____ENV_INSTANCE__-PostgresDB_Writer"
